version: '3.8'

services:
  frontend:
    build: ./ainexawebsitenext/ainexawebsitenext
    ports:
      - "3000:3000"
    restart: always

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: always
